set -sg escape-time 50

# Reload config
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded..."
# Mouse mode switch
bind-key m set-option -g mouse \; display-message "Mouse #{?mouse,ON,OFF}"
# Kill task and restart pane in the same directory
bind-key k respawn-pane -k -c "#{pane_current_path}" \; display-message "Pane restarted..."
# Switch window with Ctrl+Left and Ctrl+Right
bind-key -n C-Right next-window \; refresh-client -S
bind-key -n C-Left previous-window \; refresh-client -S

# Mouse mode default on
set -g mouse on
# Increase history size
set -g history-limit 50000

# Message in green
set -g message-style "fg=colour255 bg=colour34"

# Status bar (bottom)
set-option -g status-interval 5
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

set -g status-justify "centre"
set -g status-style "fg=black bg=colour236"

set -g status-left-style "fg=colour252 bg=colour236"
set -g status-left ""
set -g status-left-length 50

set -g status-right-style "fg=colour252 bg=colour25"
set -g status-right " #h:#S "
set -g status-right-length 50

setw -g window-status-style "fg=white bg=colour236"
setw -g window-status-format " #I #W "

setw -g window-status-current-style "fg=colour15 bg=colour25"
setw -g window-status-current-format "#[fg=colour25,bg=colour236]#[fg=colour15 bg=colour25]#I #W#[fg=colour25,bg=colour236]"

set -g pane-active-border-style "fg=colour25,bg=default"

# Top bar with left:TMUX_WORKDIR and right:TMUX_VENV
set-window-option -g pane-border-status top
set-window-option -g pane-border-format "#[fg=colour252,align=left]#{@TMUX_WORKDIR}#[fg=colour25,align=right]#{@TMUX_VENV}"
